### ISSUE TITLE
Negative values in a FloatingPointChromosome always require 64 bit

### ISSUE THREAD

**Issue by Haukinger** [giacomelli/GeneticSharp#17]
...even -1 will be represented as "11111....1111" (64 ones), independent of totalBits or fractionBits.

BTW: fractionBits should be called fractionDigits

**Comment by giacomelli** [comment]
We use the two's complement representation, this means that the high-order bit of the highest-order byte (bit 63) is interpreted as the sign bit (https://msdn.microsoft.com/pt-br/library/6wse73s4(v=vs.110).aspx). 

I think this is happening because our BinaryStringRepresentation class use a Int64 to internally provide the convertions and representations.

We'll need to figure out a way to provide the right string representation and convertions for these cases.

About the fractionBits, you're right the argument it's about the base, not about the bits used in digits. It's a really bad name, I will change it, maybe to your suggested name.

**Comment by mersadk** [comment]
+1 for renaming fractionBits to fractionDigits. It took me some time to what it really represents.

**Comment by giacomelli** [comment]
About the "negative values require 64 bit even -1 will be represented as "11111....1111" (64 ones)", as a mentioned before we use the two's complement representation, this means that the high-order bit of the highest-order byte (bit 63) is interpreted as the sign bit.

So, in the lack of a better approach to string representation positive and negative values, I will keep it as is and close this issue, but anyone can feel free to open it again if a better solution pops up.

**Comment by Haukinger** [comment]
Just cropping seems to work:

	public static string ToRepresentation(long value, int totalBits, bool throwsException)
	{
		var result = Convert.ToString(value, 2);
        if (result.Length>totalBits)
		    result = result.Substring( result.Length-totalBits, totalBits );
        if (value >= 0)
		    result = result.PadLeft( totalBits, '0' );

		if (value != ToInt64( result ) && throwsException)
		{
		    throw new ArgumentException( "The value {0} cannot be represented in {1} total bits.".With( value, totalBits ), nameof( value ) );
		}

		return result;
	}

The exception is different now, but the required bit count wasn't correct for negative numbers in the first place, anyway. Check and exception can be done similarily in the `ToRepresentation` overload for double.

Test here:

	[Test]
	public void ToFloatingPoint_ShortNegativeValue_Double()
	{
	    RandomizationProvider.Current = Substitute.For<IRandomization>();
	    RandomizationProvider.Current.GetDouble( -2.5, 0.5 ).Returns( -1.1 );

	    var target = new FloatingPointChromosome( -2.5, 0.5, 10, 2 );
	    Assert.AreEqual( "1110010010", target.ToString() );

	    var actual = target.ToFloatingPoint();
	    Assert.AreEqual( -1.1, actual );
	}
