### ISSUE TITLE
External loop control

### ISSUE THREAD

**Issue by constructor-igor** [giacomelli/GeneticSharp#53]
Hi,

We made feasibility of **GeneticSharp** and now we investigate how GeneticSharp can be integrated with our system and found a next issue: our system manages external loop and requires to get population to calculate Fitness and set calcualted Fitness values to algorithm. So, I cannot calculate fitness in CreateNewGeneration (as suggested in #45).

sample of pseudo code:
```c#
while (geneticAlgoritm.InProgress){
    population = geneticAlgoritm.GetPopulation();
    CalculateFitness(population) // [our code] calculate and set Fitness value to each chromosome
    geneticAlgoritm.SetFitness(population)
}
```

Looks, I need find loop inside GeneticSharp and, somehow, to re-implement for our control.
Please, could you help me to understand what is the easiest way to implement the feature and I'll try to do it.

thank you,
Igor.

**Comment by giacomelli** [comment]
Part of  the loop is performed here: https://github.com/giacomelli/GeneticSharp/blob/master/src/GeneticSharp.Domain/GeneticAlgorithm.cs#L315

and here: https://github.com/giacomelli/GeneticSharp/blob/master/src/GeneticSharp.Domain/GeneticAlgorithm.cs#L356

However, I did not understand why you cannot use the solution from #45, because as you can see [here](https://github.com/giacomelli/GeneticSharp/blob/master/src/GeneticSharp.Domain/GeneticAlgorithm.cs#L356) every generation evolved calls the `Population.CreateNewGeneration(newGenerationChromosomes)`. 

Please, could you explain better why you cannot use `CreateNewGeneration`?

**Comment by constructor-igor** [comment]
I investigated code in your suggestion.
Now, I better understand how can I change code for our integration.
Thank you!

**Comment by giacomelli** [comment]
Nice! Let me know if you will need any advice in the future and whether your integration worked.

**Comment by constructor-igor** [comment]
Please, could you help me to understand next issue:
I cannot compile class GeneticAlgorithm, because a error in line:
https://github.com/giacomelli/GeneticSharp/blob/ac17144427e31f2a073cac87a79ae14a4912e013/src/GeneticSharp.Domain/GeneticAlgorithm.cs#L427


![image](https://user-images.githubusercontent.com/1849690/50383455-5c14dc00-06bc-11e9-9dd2-c7d2fc05ab07.png)
